name: Create release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
          
      - name: Run tests
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      
      - name: Upload coverage report to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
          
  create_release:
    name: Create release
    if: contains(github.event_name, 'push')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name $GITHUB_ACTOR
        
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 10.x

      - name: Install standard-version package
        run: npm i standard-version

      - name: Retrieving current version from version.json
        run: echo ::set-env name=current_version_number::$(node -p "require('./version').version")
      
      - name: Create .versionrc for standard-version
        run: echo "{\"bumpFiles\":[{\"filename\":\"version.json\", \"type\":\"json\"}]}" > .versionrc
      
      - name: Create release with standard-version
        run: ./node_modules/.bin/standard-version 
      
      - name: Retrieving new version from version.json
        run: echo ::set-env name=new_version_number::$(node -p "require('./version').version")
      
      - name: Set release body
        run: echo ::set-env name=release_body::$(echo "${{ github.event.head_commit.message }}" | sed 1d)
      
      - name: Push changed files
        if: env.current_version_number != env.new_version_number
        run: git push origin master

      - name: Create github release
        if: github.ref == 'refs/heads/master' && env.current_version_number != env.new_version_number
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.new_version_number }}
          release_name: Release v${{ env.new_version_number }}
          body: |
            This is an automated release.
            ${{ env.release_body }}
          draft: false
          prerelease: false
